version: '3.7'

services:
  forex-arbitrage-api:
    container_name: forex-arbitrage-api
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - '9000:9000'